## Configurações padrão para o módulo ${artifactId}
# Uso de namespaces evita conflitos entre módulos
# Exemplo de configuração de Kafka (Inbound/Outbound)
mp.messaging.incoming.${artifactId}-in.connector=smallrye-kafka
mp.messaging.incoming.${artifactId}-in.topic=${artifactId}-input-topic
mp.messaging.outgoing.${artifactId}-out.connector=smallrye-kafka
mp.messaging.outgoing.${artifactId}-out.topic=${artifactId}-output-topic
# Configuração de gRPC
quarkus.grpc.clients.${artifactId}.host=localhost
quarkus.grpc.clients.${artifactId}.port=9000
# Variável customizada para o UseCase
${artifactId}.validacao.ativa=true
